### ISSUE TITLE
The hyperspectral images cannot be downloaded

### ISSUE THREAD

**Issue by tulilin** [Romain3Ch216/TlseHypDataSet#3]
Dear authors,

Thank you so much for your contribution of the Toulouse Hyperspectral Dataset!

When I tried to download the hyperspectral images in https://camcatt.sedoo.fr/catalogue/, I selected a tile and pushed the button on the bottom-right corner (Fig. 1). However, after loading for a while (Fig. 2), the button restored to its origin (Fig. 1) without any downloading message. Do you know where is the problem?

Thank you so much,

Best regards.

Fig. 1

![image](https://github.com/Romain3Ch216/TlseHypDataSet/assets/48641447/2c8377d9-3638-4eb4-a141-bc7784213d4e)

Fig. 2

![image](https://github.com/Romain3Ch216/TlseHypDataSet/assets/48641447/9747587f-b770-420e-837a-380dffada8db)

**Comment by adamjstewart** [comment]
I have this same problem, did you ever figure out how to download the data?

**Comment by tulilin** [comment]
> I have this same problem, did you ever figure out how to download the data?

I have solved this problem by removing the blocking from the browser after pushing the downloading botton. It is recommended to pay attention to whether there is blocking from your browser.

**Comment by adamjstewart** [comment]
Thanks, that was indeed the issue for me too!

**Comment by adamjstewart** [comment]
My connection keeps being reset halfway through the download and when I try to resume the download it says the file is no longer available on the site. I have a stable wired 1 Gbps ethernet connection, so I don't think the issue is on my side. Any suggestions?

**Comment by tulilin** [comment]
> My connection keeps being reset halfway through the download and when I try to resume the download it says the file is no longer available on the site. I have a stable wired 1 Gbps ethernet connection, so I don't think the issue is on my side. Any suggestions?

I also encountered this problem sometimes. I only tried more times.

**Comment by adamjstewart** [comment]
I've tried about a dozen times over the course of several days and have yet to successfully download a single tile. Can anyone upload the files on Hugging Face so they can be more easily downloaded?

**Comment by Romain3Ch216** [comment]
Hello everyone,

Sorry for the late reply. The server is indeed quite unstable. Some issues have been solved in the past weeks. Unfortunately, the images are only available on the sedoo catalogue for now...

If you are only interested in 1D (i.e. spectral) processing, spectra + ground truth are available on Hugging Face:
https://huggingface.co/datasets/Romain3Ch216/TlseHypDataSet

I will consider with colleagues to upload the images on HuggingFace.

Best,
Romain
